module.exports = {
  REQUEST_TYPES: {
    VACATION: 'VACACIONES',
    SICK_LEAVE: 'LICENCIA MEDICA',
    EXPENSES: 'GASTOS',
    GENERAL: 'ASUNTOS GENERALES'
  },
  STATUS: {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED'
  }
};